name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0 
  flutter_image_slideshow: ^0.1.6
  motion_tab_bar: ^2.0.4
  salomon_bottom_bar: ^3.3.2
  dio: ^5.7.0
  navigation_view: ^1.0.6
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^8.1.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - Images/
  fonts:
    - family: IBMP
      fonts:
        - asset: fonts/IBMPlexSans-Medium.ttf
    - family: IBMP2
      fonts:
        - asset: fonts/IBMPlexSans-Italic.ttf
        

    # - family: RobotoMono
    #   fonts:
    #     - asset: fonts/RobotoMono-Regular.ttf
    #     - asset: fonts/RobotoMono-Bold.ttf
    #       weight: 700
